<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    
    <PackageReference Include="Nancy" Version="2.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="14.0.1-beta2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Keeltekool_2.ApplicationServices\Keeltekool_2.ApplicationServices.csproj" />
    <ProjectReference Include="..\..\Keeltekool_2.Core\Keeltekool_2.Core.csproj" />
    <ProjectReference Include="..\..\Keeltekool_2.Data\Keeltekool_2.Data.csproj" />
	      <ProjectReference Include="..\..\Keeltekool_2.xUnitTesting\Keeltekool_2.xUnitTesting.csproj" />

    <Project Path="../KeelteKoolV2.xUnitTesting/KeelteKoolV2.xUnitTesting.csproj" Id="a0d54aa4-c177-4449-8d9e-0a0b8b668389" />    </ItemGroup>

</Project>
